version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-attendance
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
    ports:
      - "5440:5432"
    volumes:
      - pgdata-attendance:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-attendance
    ports:
      - "3008:3008"
    depends_on:
      - postgres
    volumes:
      - ./Backend:/app

  employee-attendance-ui:
    build:
      context: ./employee-attendance
      dockerfile: Dockerfile
    container_name: employee-attendance-ui
    ports:
      - "8012:80"

  hr-attendance-ui:
    build:
      context: ./hr-attendance
      dockerfile: Dockerfile
    container_name: hr-attendance-ui
    ports:
      - "8013:80"

volumes:
  pgdata-attendance:

