# Use Node.js LTS image
FROM node:18

# Set working directory
WORKDIR /app

# Copy dependencies and install
COPY package*.json ./
RUN npm install

# Copy all other files
COPY . .

# Expose port
EXPOSE 3017

# Start the server
CMD ["node", "server.js"]

